// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqfTNc7X_NSIjFpnRsjEi5G8IYX-AZmTs',
    appId: '1:895894180005:web:1b78e2ab49793ad2cf7d4c',
    messagingSenderId: '895894180005',
    projectId: 'medhub-d9cfb',
    authDomain: 'medhub-d9cfb.firebaseapp.com',
    storageBucket: 'medhub-d9cfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzUbmMwzRKUyqzVHoQbHYc1vAg-Vrslk',
    appId: '1:895894180005:android:52e59f579a63b035cf7d4c',
    messagingSenderId: '895894180005',
    projectId: 'medhub-d9cfb',
    storageBucket: 'medhub-d9cfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNIW5pXfdHyKnoNZulkybxiNzTCglrrg4',
    appId: '1:895894180005:ios:b3296ea5e773ec84cf7d4c',
    messagingSenderId: '895894180005',
    projectId: 'medhub-d9cfb',
    storageBucket: 'medhub-d9cfb.appspot.com',
    iosBundleId: 'com.example.pharmacyWarehouseStoreMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNIW5pXfdHyKnoNZulkybxiNzTCglrrg4',
    appId: '1:895894180005:ios:d3ba26cc195f21edcf7d4c',
    messagingSenderId: '895894180005',
    projectId: 'medhub-d9cfb',
    storageBucket: 'medhub-d9cfb.appspot.com',
    iosBundleId: 'com.example.pharmacyWarehouseStoreMobile.RunnerTests',
  );
}
